language: rust
os: linux
cache: cargo
jobs:
  include:
    - dist: xenial
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      osx_image: xcode9.4
      rust: stable
    - os: windows
      rust: stable
before_script:
  - rustup component add clippy
script:
  - cargo build
  - cargo clippy
