sudo: false
language: rust
cache: cargo
matrix:
  include:
    - os: linux
      dist: xenial
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      osx_image: xcode9.4
      rust: stable
    - os: windows
      rust: stable
  - rustup component add clippy
script:
  - cargo build
  - cargo clippy
